refactor: rebrand wallet welcome page ROLLUP-171 (#7)
* Changes to make it work with a local npm zksync with rsk code, npm link is required

* PP-178: Update links to have more cover in rsk port.

* PP-178: remove redundant else

* PP-178: Remove uptime from footer and hide checkout on the navbar

* Update the explorer links to work with localhost (#2)

* Update the explorer links to work with localhost

* PP-172: Added missing references to explorer in localhost

* PP-172: Update explorer url depending of explorer version

* PP-172: Remove explorer version for unused env files

* PP-172: remove explorer version in env.ropsten-beta

* PP-277: Fix explorer links on testnet (#5)

* PP-277: Fix explorer links on testnet
* PP-277: Remove unused env files. Added extra explorer variable for L1 links
* PP-277: fix the ZK_SPECIAL_API param and add testnet commands
Co-authored-by: Antonio Morrone <antonio@iovlabs.org>

* PP-181: Update wallet to use the references to new js package.  (#6)

* PP-181: Update wallet to use the references to new js package. Replace zksync js with rif-aggregation release

* PP-181: remove unnecessary changes

* PP-181: update references for sdk package

* PP-181: Fix the npm package source

* PP-181: update yarn lock dependency and remove package-lock.json

* refactor: forking from matter-labs master commit 107361b

* refactor: update to last version matterlabs zksync wallet

* refactor: wip fail toremove @matterlabs dependencies and add them to the original wallet Nuxt fatal error: TypeError: id.startsWith is not a function

* refactor: wip Nuxt fatal error: TypeError: id.startsWith is not a function

* refactor: wip change version of husky and nuxt  Nuxt fatal error: TypeError: id.startsWith is not a function

* refactor: wip adding module to nuxt.config Nuxt fatal error: TypeError: id.startsWith is not a function

* refactor: updating to last versionn of zksync-wallet-vue

* refactor: rebranding logo and colors

* refactor: fixing box background color and typo in color name

* refactor: removing not supported wallets

* fix: center welcome page items

* refactor: removing era announcement

* refactor: changing colors and alignments

* refactor: adding Sora font

* fix: button colors

* fix: balance list colors

* fix: restoring rif wallet workflows

* fix: updating workflows

* fix: change rollup-nuxt-core url and commenting firebase references on workflows

* refactor: update README

* refactor: change favicon

---------

Co-authored-by: Raul Laprida <raul@iovlabs.org>
Co-authored-by: Alan Hurtarte <alan.hurtarte@iovlabs.org>
Co-authored-by: Antonio Morrone <dev@antomor.com>
Co-authored-by: Alan Hurtarte <alan220193@hotmail.com>
Co-authored-by: Anni Piragauta <annipi@Annis-MacBook-Pro.local>